### ISSUE TITLE
Feature Request: A way to abort the message.

### ISSUE THREAD

**Issue by aarcro** [hirokiky/django-reportmail#7]
I have a use case where I don't always want to send the report from a command. It would be handy to have something like reporter.abort() to cause no message to be send.

**Comment by bphirokiky** [comment]
thanks for your proposal! it would be great feature.

**Comment by hirokiky** [comment]
thanks for your proposal! it would be great feature.

**Comment by hirokiky** [comment]
Added docs, described about you on AUTHORS and released new django-reportmail 1.3 https://pypi.python.org/pypi/django-reportmail/1.3.
